title: Michael Monteleone
url: http://michaelmonteleone.net
description: 'Personal site of Michael Monteleone, software developer and designer from New Orleans'
keywords:
 - Michael Monteleone
 - Mike Monteleone
 - namelessmike

author:
    name: Michael Monteleone
    email: michael@michaelmonteleone.net
    twitter: http://twitter.com/namelessmike
    github: http://github.com/mmonteleone
    delicious: http://delicious.com/namelessmike
    pinboard: http://pinboard.in/u:namelessmike
    googleplus: http://plus.google.com/100369739207842495161
    facebook: http://www.facebook.com/michael.monteleone
    linkedin: http://www.linkedin.com/in/michaelmonteleone/
    avatar: http://www.gravatar.com/avatar/392da320b3aa4068d0b03024135875fb?s=70
    openid:
        server: https://www.google.com/accounts/o8/ud
        delegate: http://www.google.com/profiles/namelessmike
    
sections:
 - projects
 - about
 - journal 
stylesheets:
 - /assets/themes/default/css/screen.css?52480=52480
 - /assets/themes/default/css/print.css
scripts:
 - http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js    
 - /assets/themes/default/js/site.min.js?131513?131513
colors:
    highlights:
        blue: '#009ff7'
        green: '#87d14b'
        red: '#FF007C'
    mono:
        dark: '#000000'
        medium: '#777777'
        light: '#FFFFFF'
    bg: '#EAF1F4'
    
pygments: true
permalink: pretty 
exclude:
 - Rakefile
 - README.markdown
 - .git
